### ISSUE TITLE
Few Fixes

### ISSUE THREAD

**Issue by ThomasThelen** [JordanHoover/cpp-practice#1]
<h1>Take out `using namsepsace std`</h1>
Notice that you're only using one function inside all of the standard namespace. Instead of bringing _all_ of it in, why not just call the function as `std::cout<<"Calculate Area of a Circle of 12 radius: " << calculateAreaOfCircle(12);`

<h1>Use `double` instead of `float`</h1>
Unless you have a reason to, use `double` over float.

<h1>Use `auto`</h1>
Since the type of `areaofCircle` will be decided by the stuff to the right of it, declare it as
`auto areaOfCircle = PI * radius * radius;`
In the case that you change the type of `PI`, or `radius`, you won't have to go back and change it for `areaofCircle`.

**Comment by JordanHoover** [comment]
Thanks for the feedback!  I googled your suggested changes and why they should be made and then made the updates.

**Comment by ThomasThelen** [comment]
If you're interested in really kicking C++ off,  I would recommend any of the Scott Meyers books. Just make sure you're using "[modern C++](https://stackoverflow.com/questions/536439/is-modern-c-becoming-more-prevalent)"-employers love it, and it's really fun!

Nice resume by the way-that's a nice combo of finance and CS. Have you thought about applying at Schwab? I'm actually working on a project that has a few folks from University of Illinois.

**Comment by JordanHoover** [comment]
Thanks - I have been thinking about checking out his Effective Modern C++ book or something similar.  I have a list of companies near me in the Phoenix area that I am going to check out for jobs to apply to, and I have added Schwab to my list.

And again, thanks for taking the time to look at my code and give advice/feedback.  Much appreciated.
